### ISSUE TITLE
CasperJS run in integration-test phase

### ISSUE THREAD

**Issue by vilmosnagy** [casperjs/casperjs-runner-maven-plugin#15]
Hi!

I'd like to run my casperJS tests in the `integration-test` phase, 'cause

 * I'll have to prepare a database with the correct data (in the `pre-integration-test` phase), 
 * I'll have to start a Jetty server with my application (in the `pre-integration-test` phase),
 * and I would like to stop the jetty server after the integration test run (in the `post-integration-test` phase)

If I config the plugin to run in the `integration` phase then if there are any failed test, the `post-integration-phase` won't run, and the Jetty server'll be stuck. Is there a way to run the tests in the `integration-test` phase, but fail in the `verify` phase, if there's any error? (Like maven failsafe plugin does)

Or do I have to write this myself?

Thanks,

**Comment by bguerin** [comment]
Hello, I will look at how the failsafe plugin works and try to adapt this plugin

**Comment by bguerin** [comment]
I checked the code of the failsafe plugin and this is exactly how it works, so your PR is welcome !

**Comment by vilmosnagy** [comment]
Thanks. 

I'm gonna write a sample for it tomorrow, and create the pr.
