### ISSUE TITLE
CasperJSRuntimeFinder assumes casperjs.bat exists on filesystem

### ISSUE THREAD

**Issue by jdavis61** [casperjs/casperjs-runner-maven-plugin#9]
I am receiving a MojoFailureException with the message ""Unable to determine casperJS version" when using the casperjs-runner-maven-plugin on a Windows 10 machine. The reason for the failure is the CasperJsRuntimeFinder findCasperRuntime method assumes casperjs.bat is in the casperjs bin directory.

Changing line 39 of this method to defaultCasperRuntime = "casperjs.exe"; resolved this issue. Not sure if casperjs.bat has been removed from newer versions of casperjs. 

I am using casperjs version 1.1.1 dowloaded from their github repo. 

The above issue is present in the casperjs-runner-maven-plugin 1.0.3 and 1.0.4.

**Comment by bguerin** [comment]
@jdavis61 : sorry for all this time of ... nothing ...
I fix the plugin this afternoon, and just release a 1.0.4 version of the plugin. Enjoy !

**Comment by jdavis61** [comment]
No problem! Thank you for fixing the issue and maintaining this plugin.
